//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace portafolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicios
    {
        public string Id { get; set; }
        public string UsuarioID { get; set; }
        public string Descripcion { get; set; }
        public string Servicio { get; set; }
        public string Descripcion_Servicio { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
